-- 1. APP SETTINGS (Configuración Global)
CREATE TABLE IF NOT EXISTS public.app_settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    app_name TEXT NOT NULL DEFAULT 'GalgoTrack',
    app_logo_url TEXT,
    ticket_name TEXT NOT NULL DEFAULT 'CONSORCIO GALGOTRACK',
    ticket_logo_url TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insertar configuración inicial si no existe
INSERT INTO public.app_settings (id, app_name, ticket_name)
VALUES (1, 'GalgoTrack', 'CONSORCIO GALGOTRACK')
ON CONFLICT (id) DO NOTHING;

-- 2. PROFILES (Usuarios y Roles)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
    name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'Moderador',
    consortium_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TERMINALS (Máquinas)
CREATE TABLE IF NOT EXISTS public.terminals (
    id TEXT PRIMARY KEY,
    owner_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    address TEXT,
    phone TEXT,
    manager TEXT,
    type TEXT,
    status TEXT DEFAULT 'Desconectado',
    last_sync TIMESTAMPTZ,
    ip_address TEXT,
    software_version TEXT,
    ini_content JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TRANSACTIONS (Finanzas)
CREATE TABLE IF NOT EXISTS public.transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    terminal_owner_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    terminal_id TEXT REFERENCES public.terminals(id) ON DELETE CASCADE,
    machine_name TEXT,
    type TEXT CHECK (type IN ('BET', 'PAYOUT')),
    amount NUMERIC NOT NULL DEFAULT 0,
    ticket_id TEXT
);

-- 5. JACKPOT (Valores Realtime)
CREATE TABLE IF NOT EXISTS public.jackpot_values (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    current_value NUMERIC NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insertar jackpot inicial
INSERT INTO public.jackpot_values (id, current_value)
VALUES (1, 0)
ON CONFLICT (id) DO NOTHING;

-- 6. NOTIFICATIONS (Alertas)
CREATE TABLE IF NOT EXISTS public.notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT CHECK (type IN ('connection', 'disconnection', 'alert')),
    read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- SEGURIDAD (RLS)
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.terminals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jackpot_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Políticas Básicas (Lectura permitida para autenticados)
CREATE POLICY "Public app_settings are viewable by everyone" ON public.app_settings FOR SELECT USING (true);
CREATE POLICY "Profiles are viewable by owners" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Terminals are viewable by owners" ON public.terminals FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "Transactions are viewable by terminal owners" ON public.transactions FOR SELECT USING (auth.uid() = terminal_owner_id);
CREATE POLICY "Jackpot is viewable by everyone" ON public.jackpot_values FOR SELECT USING (true);
CREATE POLICY "Notifications are viewable by everyone" ON public.notifications FOR SELECT USING (true);
